// <auto-generated />
namespace AppStudio.Menu.BackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class V_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201408162000538_V_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
